#ifndef _PARAMETERS_H_
#define _PARAMETERS_H_

#define KACHI 1 // 1号(1軍) or 2号(2軍)

/////////// Debug family /////////////
#define beep() { Speaker s; s.playTone(33, 500, 50); }
#define TORQUE_MOTOR 1
#define BEEP_AT_TRIGER 1
#define PRINT_CALC_DIRECTION_OFFSET_90 0
#define PRINT_STATE 1
#define PRINT_THREAD_TIME 0
#define PRINT_PID_CONTROLLER 0
#define PRINT_LINE_TRACE_DRIVER 0
#define PRINT_DIRECTION_PID_DRIVER 0
#define PRINT_CURVATURE_PID_DRIVER 0
//////////////////////////////////////

enum EDGE{NONE=0,LEFT,RIGHT};
enum EDGE TRACED_EDGE = RIGHT;

#define LIGHT_SENSOR_PORT PORT_3
#define LEFT_TOUCH_PORT   PORT_1
#define RIGHT_TOUCH_PORT  PORT_4
#define LEFT_MOTOR_PORT   PORT_C
#define RIGHT_MOTOR_PORT  PORT_B
#define GYRO_SENSOR_PORT  PORT_2

#define WHEEL_RADIUS   4.08 // cm
#define WHEEL_DISTANCE 6.5 // cm

// Direction direction offset
#define DIRECTION_DEGREE_OFFSET_90_TRIGER_DEGREE_DERIVATIVE_BOUNDS 10
#define DIRECTION_DEGREE_OFFSET_90_TRIGER_DEGREE_LOWER 70
#define DIRECTION_DEGREE_OFFSET_90_TRIGER_FLAGCOUNT 100

#define DIRECTION_DEGREE_OFFSET_180_TRIGER_DEGREE_DERIVATIVE_BOUNDS 7.5
#define DIRECTION_DEGREE_OFFSET_180_TRIGER_DEGREE_LOWER 160
#define DIRECTION_DEGREE_OFFSET_180_TRIGER_DEGREE_UPPER 200
#define DIRECTION_DEGREE_OFFSET_180_TRIGER_FLAGCOUNT 50

// Direction PID parameters
// Kc = 40, Tc = 60 とした限界感度法
#define DIRECTION_PID_KP 24.0
#define DIRECTION_PID_KI 0.8
#define DIRECTION_PID_KD 180.0
#define DIRECTION_PID_SIZE 1

// Curvature PID parameters
#define CURVATURE_PID_KP 1.0
#define CURVATURE_PID_KI 0.0
#define CURVATURE_PID_KD 0.0
#define CURVATURE_PID_SIZE 10
#define CURVATURE_PID_DERIVATIVE_INTERVAL 10
#define ALLOWABLE_CURVATURE 0.3 // 半径3cmの円
#define MAX_CURVATURE 0.03 // ライントレース中データより

// ジャイロオフセット
#if KACHI == 2
#define USER_GYRO_OFFSET 604 // old gyro
#elif KACHI == 1
#define USER_GYRO_OFFSET 590 // new gyro
#endif

// 光センサ
#if KACHI == 2

/// 地区大会
// white 523
// gray 623
// black 690
//#define WHITE_GRAY_THRESH 550 // 555
//#define BLACK_MEAN 640 // 698
/// 瀬尾宅
//#define WHITE_MEAN 550
//#define GRAY_MEAN 640
//#define BLACK_MEAN 700
//#define WHITE_GRAY_THRESH 575
/// 4F-会議室A
#define WHITE_MEAN 560
#define GRAY_MEAN 650
#define BLACK_MEAN 750
#define WHITE_GRAY_THRESH 585
/// チャンピオンシップ試走会
//#define WHITE_MEAN 540
//#define GRAY_MEAN 640
//#define BLACK_MEAN 730
//#define WHITE_GRAY_THRESH 570

#elif KACHI == 1

/// 4F-会議室A
#define WHITE_MEAN 560
#define GRAY_MEAN 650
#define BLACK_MEAN 740
#define WHITE_GRAY_THRESH 585
#define BLACK_GRAY_THRESH 695

#endif

#if 0
/// Light PID
// S8 SPEED = 50; // OUT 50 IN 60
// F32 KP = 40;//0.8;  ///< 比例ゲインのデフォルト値。1.0
// F32 KI = 0;//0.02; ///< 積分ゲインのデフォルト値。
// F32 KD = -10;//-2.0; ///< 微分ゲインのデフォルト値。-0.5
//LightPid: SPEED vs KP
// 50 vs 40 OK
// 60 vs 40 NG
// 60 vs 60 NG
/// obsolete
// F32 KP = 0.8;  ///< 比例ゲインのデフォルト値。1.0
// F32 KI = 0.02; ///< 積分ゲインのデフォルト値。
// F32 KD = -2.0; ///< 微分ゲインのデフォルト値。-0.5
// S8 SPEED = 50; // OUT 50 IN 60
#endif
#define PID_LIMITED_SPEED 30

/// Line Trace
#if 1 // 4F-A会議室
// ALG 4
// 70, 20, 0, 20, 2 OK
// 75, 20, 0, 20, 2 一応OK
// 80, 20, 0, 40, 2 OK
// 90, 20, 0, 40, 2 NG - 急Ｓ字に入らなければOK
// 90, 30, 0, 40, 2 NG
// 85, 25, 0, 40, 2 怪しい
S8 SPEED = 100;
F32 KP = 20;
F32 KI = 0;
F32 KD = 40;
F32 ENHANCE_Y_FOR_BLACK_COEF = 2.0;
U32 DERIVATIVE_INTERVAL = 300;
#endif
#if 0 // CS大会試走会
// K_THETA 110 OK
// K_THETA 115 OK
// K_THETA 120 NG
S8 SPEED = 100; 
F32 KP = 20;
F32 KI = 0;
F32 KD = 40;
F32 ENHANCE_Y_FOR_BLACK_COEF = 2.0;
U32 DERIVATIVE_INTERVAL = 300;
#endif
S8  START_BOOT_SPEED = 60;
int START_BOOT_TIME  = 1800; // ms
S8  GOAL_STOP_STRATEGY_SPEED = SPEED;

// Goal
#define OUT_DISTANCE_TO_GOAL 270 // 300 // 305 //cm(in course)
#define IN_DISTANCE_TO_GOAL 240 // 270 // 275
#define GOAL_STOP_STRATEGY_TRIGER_DEGREE_DERIVATIVE_BOUNDS 15
#define GOAL_STOP_STRATEGY_TRIGER_DEGREE 320
#define GOAL_STOP_STRATEGY_TRIGER_FLAGCOUNT 100
#define GOAL_STOP_STRATEGY_STOP_VELOCITY_X 0
#define GOAL_STOP_STRATEGY_STOP_VELOCITY_Y 10 // 0
#define GOAL_STOP_STRATEGY_STOP_REFERENCE_DEGREE 360 // 0
#define GOAL_STOP_STRATEGY_FIRST_STOP_TIME 5000
#define GOAL_STOP_STRATEGY_SECOND_STOP_TIME 3500
#define GOAL_STOP_STRATEGY_REPEATED_DISTANCE 20

// Dashed
#define DASHED_LINE_STRATEGY_TRIGER_DEGREE 170
#define DASHED_LINE_STRATEGY_TRIGER_RAW_DEGREE_LOWER 178.5
#define DASHED_LINE_STRATEGY_TRIGER_RAW_DEGREE_UPPER 181.5

#define DASHED_LINE_STRATEGY_STRAIGHT_DIRECTION_TO_GO 185 // 180 /* 破線走行1回目の目標値 */
#define DASHED_LINE_STRATEGY_STRAIGHT_DIRECTION_TO_GO_SPEED 100
#define DASHED_LINE_STRATEGY_DISTANCE_TO_LAND 105 // 115 // cm

#define DASHED_LINE_STRATEGY_STRAIGHT_DIRECTION_TO_LAND 192 // 185 /* 破線走行2回目の目標値 */
#define DASHED_LINE_STRATEGY_STRAIGHT_DIRECTION_TO_LAND_SPEED 20 // 30

// NewDashed(From in course)
#define NEW_DASHED_LINE_SECTION_TRIGER_DEGREE 160
#define NEW_DASHED_LINE_SECTION_TRIGER_RAW_DEGREE_LOWER 170.5
#define NEW_DASHED_LINE_SECTION_TRIGER_RAW_DEGREE_UPPER 173.5

#define NEW_DASHED_LINE_SECTION_STRAIGHT_DIRECTION_TO_GO 178 // 180 /* 破線走行1回目の目標値 */
#define NEW_DASHED_LINE_SECTION_STRAIGHT_DIRECTION_TO_LAND 192

#define NEW_DASHED_LINE_SECTION_STRAIGHT_DIRECTION_TO_GO_SPEED 100
#define NEW_DASHED_LINE_SECTION_DISTANCE_TO_LAND 110 // 115 // cm

//#define NEW_DASHED_LINE_SECTION_STRAIGHT_DIRECTION_TO_LAND 190 // 185 /* 破線走行2回目の目標値 */
#define NEW_DASHED_LINE_SECTION_LANDING_DIRECTION_DIFF 5.0
#define NEW_DASHED_LINE_SECTION_STRAIGHT_DIRECTION_TO_LAND_SPEED 20 // 30

// treasurehunt
#define TREASURE_HUNT_STRATEGY_TRIGER_DEGREE 250
#define TREASURE_HUNT_STRATEGY_TRIGER_RAW_DEGREE_LOWER 268.5
#define TREASURE_HUNT_STRATEGY_TRIGER_RAW_DEGREE_UPPER 271.5
#define TREASURE_HUNT_STRATEGY_TRIGER_DEGREE_DERIVATIVE_BOUNDS 15

#define TREASURE_HUNT_STRATEGY_TRIGER_FLAGCOUNT 20

#define TREASURE_HUNT_STRATEGY_FORWARD_VELOCITY_X 100
#define TREASURE_HUNT_STRATEGY_FORWARD_DISTANCE 35 // cm

#define TREASURE_HUNT_STRATEGY_BACKWARD_DIRECTION_DIFF -20
#define TREASURE_HUNT_STRATEGY_BACKWARD_VELOCITY_X -80 // - 70
#define TREASURE_HUNT_STRATEGY_BACKWARD_DISTANCE -30

#define TREASURE_HUNT_STRATEGY_LANDING_VELOCITY_X 30 // 20
#define TREASURE_HUNT_STRATEGY_LANDING_DIRECTION_DIFF 40


// new treasure hunt
#define NEW_TREASURE_HUNT_STRATEGY_TRIGER_DEGREE 250
#define NEW_TREASURE_HUNT_STRATEGY_TRIGER_RAW_DEGREE_LOWER 268.5
#define NEW_TREASURE_HUNT_STRATEGY_TRIGER_RAW_DEGREE_UPPER 271.5
#define NEW_TREASURE_HUNT_STRATEGY_TRIGER_DEGREE_DERIVATIVE_BOUNDS 15

#define NEW_TREASURE_HUNT_STRATEGY_STATE_3_DISTANCE 50
#define NEW_TREASURE_HUNT_STRATEGY_LANDING_DISTANCE 40
#define NEW_TREASURE_HUNT_STRATEGY_LANDING_DIRECTION -5

// Dolphin
#define DOLPHIN_STRATEGY_TRIGER_DEGREE 200 // 210 // 200
#define DOLPHIN_STRATEGY_TRIGER_FLAGCOUNT 20

#define DOLPHIN_STRATEGY_STRAIGHT_DIRECTION_TO_GO 210 // 230 // 210
#define DOLPHIN_STRATEGY_STRAIGHT_DIRECTION_TO_GO_SPEED 90 // 90 // 90
#define DOLPHIN_STRATEGY_DISTANCE_TO_LAND 75 // 80 // 75 cm

#define DOLPHIN_STRATEGY_STRAIGHT_DIRECTION_TO_LAND 150
#define DOLPHIN_STRATEGY_STRAIGHT_DIRECTION_TO_LAND_SPEED 20

#define DOLPHIN_STRATEGY_LANDING_BOOT_SPEED 40
#define DOLPHIN_STRATEGY_LANDING_BOOT_TIME 2300 // ms
#define DOLPHIN_STRATEGY_LANDING_SPEED 90

// twinloop
//#define TWINLOOP_STRATEGY_TRIGER_DEGREE 179
//#define TWINLOOP_STRATEGY_TRIGER_DEGREE_DERIVATIVE_BOUNDS 10
//#define TWINLOOP_STRATEGY_TRIGER_FLAGCOUNT 10
// Now the triger is the 180 offset.

#define TWINLOOP_STRATEGY_LINETRACE_DISTANCE 36.0
#define TWINLOOP_STRATEGY_LINETRACE_DISTANCE_FOR_DOLPHIN 43.5

#define TWINLOOP_STRATEGY_FORWARD_VELOCITY_X 80
#define TWINLOOP_STRATEGY_FORWARD_REFERENCE_DEGREE 270
#define TWINLOOP_STRATEGY_FORWARD_DISTANCE 42.5 // cm

#define TWINLOOP_STRATEGY_BACKWARD_VELOCITY_X -60
#define TWINLOOP_STRATEGY_BACKWARD_REFERENCE_DEGREE 270
#define TWINLOOP_STRATEGY_BACKWARD_DISTANCE 0 // 0 で十分下がる

#define TWINLOOP_STRATEGY_2ND_FORWARD_VELOCITY_X 40
#define TWINLOOP_STRATEGY_2ND_FORWARD_REFERENCE_DEGREE 270
#define TWINLOOP_STRATEGY_2ND_FORWARD_DISTANCE 42.5

#define TWINLOOP_STRATEGY_LANDING_VELOCITY_X 30
#define TWINLOOP_STRATEGY_LANDING_REFERENCE_DEGREE 370

#define TWINLOOP_STRATEGY_LANDING_BOOT_SPEED 40
#define TWINLOOP_STRATEGY_LANDING_BOOT_TIME 2500 // ms
#define TWINLOOP_STRATEGY_LANDING_BOOT_EDGE RIGHT
#define TWINLOOP_STRATEGY_LANDING_SPEED 70
#define TWINLOOP_STRATEGY_LANDING_EDGE RIGHT

// Maybe used later.
// 
// #define SAMPLING_TIME 5 // ms
// #define NUM_LIGHT_SENSOR_HISTORY    1
// #define NUM_LEFT_TOUCH_HISTORY      1
// #define NUM_RIGHT_TOUCH_HISTORY     1
// #define NUM_LEFT_MOTOR_HISTORY      300
// #define NUM_RIGHT_MOTOR_HISTORY     300
// #define NUM_GYRO_SENSOR_HISTORY     1
// #define NUM_BATTERY_VOLTAGE_HISTORY 1

#endif /* _PARAMETERS_H_ */
